name: .NET

on: push

jobs:
    Build:
        runs-on: self-hosted
        strategy:
            matrix:
                dotnet-version: ["3.1.x", "5.0.x", "6.0.x"]
        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: ${{ matrix.dotnet-version }}
            - name: Restore dependencies
              working-directory: "./JishoNET"
              run: dotnet restore
            - name: Build
              working-directory: "./JishoNET"
              run: dotnet build --no-restore
            - name: Test
              working-directory: "./JishoNET.Tests"
              run: dotnet test --no-restore --verbosity normal
